### ISSUE TITLE
Zig version

### ISSUE THREAD

**Issue by wilsonk** [greenfork/kisa#1]
Hey greenfork,

Can you list the zig version you are using to build kisa in the README somewhere, please?  I have tried head from today (0.9.0-dev.664+a8e8927c4) and 0.8.0 release but neither builds kisa.

For 0.8.0:
```
./src/main.zig:714:19: error: no member named 'sendFileToOpen' in struct 'Client'
.
.
.
```

And for 0.9.0-dev.664+a8e8927c4:
```
/home/wilsonk/krepyc/kisa/src/main.zig:597:13: error: unused local variable
.
.
.
```

**Comment by greenfork** [comment]
Hi wilsonk! Yeah, that's a good idea, I updated readme https://github.com/greenfork/kisa#how-to-build. In short it is version 0.8.0 and you probably want to run `zig build test`. Let me know if you want to know something specific, I will be glad to help, you can hit me on discord or ask right here
