### ISSUE TITLE
move design documents into separate folder ?called DESIGN?

### ISSUE THREAD

**Issue by matu3ba** [greenfork/kisa#2]
reason: remove clutter from root

**Comment by greenfork** [comment]
Yeah, I thought about moving these to documentation, probably via pandoc or something similar, here in the docs/ directory there's already some API beginnings https://greenfork.github.io/kisa/

Also, let's keep this and similar issues for now so others have an idea about what's happening. I can't keep up with expressing all the different things which need to be done this early in the project :)
